# Generated by Django 5.2.7 on 2025-10-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0003_blog_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
